# Generated by Django 5.0.4 on 2024-10-27 12:03

import django.core.validators
import furry_funnies.author.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), furry_funnies.author.validators.letters_validator], verbose_name='First Name:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='"Profile Image URL:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), furry_funnies.author.validators.letters_validator], verbose_name='Last Name:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[django.core.validators.MinLengthValidator(6, 'Your passcode must be exactly 6 digits!'), django.core.validators.MaxLengthValidator(6, 'Your passcode must be exactly 6 digits!'), furry_funnies.author.validators.passcode_validator], verbose_name='Passcode:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pets_number',
            field=models.PositiveSmallIntegerField(verbose_name='Pets Number:'),
        ),
    ]
