# Generated by Django 5.0.4 on 2024-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(help_text='Share your funniest furry photo URL!', verbose_name='Post Image URL'),
        ),
    ]
